# Generated by Django 5.0 on 2025-02-17 08:33

import django.db.models.deletion
import django.utils.timezone
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_zone', models.CharField(blank=True, max_length=50)),
                ('duration', models.DurationField()),
                ('unique_code', models.CharField(default=events.models.generate_unique_code, editable=False, max_length=6, unique=True)),
                ('is_private', models.BooleanField(choices=[(True, 'Private'), (False, 'Public')], default=True)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
