# Generated by Django 5.0 on 2025-02-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='peer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
