# Generated by Django 5.0 on 2023-12-07 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mushaf_page', '0002_mushafpage_page_number_alter_mushafpage_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('drawn_paths', models.JSONField(default=list)),
                ('mushaf_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushaf_page.mushafpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
