# Generated by Django 5.0 on 2023-12-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='drawn_paths',
            field=models.JSONField(default=list, null=True),
        ),
    ]
