# Generated by Django 5.0 on 2023-12-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0002_alter_userpage_drawn_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='camped',
            field=models.BooleanField(default=False),
        ),
    ]
