# Generated by Django 5.0 on 2025-01-01 23:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('user_page', '0003_userpage_camped'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
