# Generated by Django 5.0 on 2023-12-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushaf_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushafpage',
            name='page_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='mushafpage',
            name='image_url',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
