# Generated by Django 5.0 on 2023-12-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushaf_page', '0002_mushafpage_page_number_alter_mushafpage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushafpage',
            name='image_saved_url',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
