# Generated by Django 5.0 on 2024-12-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushaf_page', '0004_rename_image_saved_url_mushafpage_image_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushafpage',
            name='verse_ref_end',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='mushafpage',
            name='verse_ref_start',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
