# Generated by Django 5.0 on 2023-12-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='null@email.com', max_length=254, unique=True)),
                ('password', models.CharField(default='pbkdf2_sha256$720000$k9dduKNIk7r2EYZSXBJ2a3$Vk7OVdKSpLwEFpWSUZ3IpRCfbF4AB1wO80/Eo0r4zng=', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
