# Generated by Django 5.0 on 2023-12-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$aDSAKvARPn8F5jp58IOmzk$QDIXJsBAcEGYhLJDcECKnLjHrGGUtXBgpA7/RBm+oDI=', max_length=128),
        ),
    ]
