# Generated by Django 5.0 on 2023-12-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$Ysip9S34qGnp3OG0wm1MUb$fYB6XRY0H2vsjIQMk0Yqa6LJzxl2Dghd02sxFdMF0b8=', max_length=128),
        ),
    ]
