# Generated by Django 5.0 on 2023-12-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$A3wit1v9tKCi8JwNWfZIJe$MvLBAoE2MXbTMyjcZO64or7XHNgeLhvNFdK74CYMj/c=', max_length=128),
        ),
    ]
