# Generated by Django 5.0 on 2023-12-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$obBUal843o0FoQeBgBAa8U$Esy+ACgBuD510bWtZbiwEBk47CV5Jb91fTa2kjJBJlA=', max_length=128),
        ),
    ]
