# Generated by Django 5.0 on 2023-12-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$rBLwFBNO1Di6GuNtV3BxzV$8N0lwS8+cN5iTDfOR4sfcFqHhhq88g5viOR2zT9WySo=', max_length=128),
        ),
    ]
