# Generated by Django 5.0 on 2023-12-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$bgmV7i1bQwUPPIUGwsOeJV$BfnM2bRGdT1umzOIjBCm/BnCa+T2WjPlnGnOGCP9XQs=', max_length=128),
        ),
    ]
