# Generated by Django 5.0 on 2023-12-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$mxg02HMVC6tkumERxeFdBh$iPKnhFL209s8wjHXa73tfYHlTUWr/6XJeYo5P/fuk5c=', max_length=128),
        ),
    ]
