# Generated by Django 5.0 on 2023-12-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$eesJruKd9ij5XHpiFhmFek$/pz+KVUeBokkL7LZyfpws8R5j/8RkQYOD5Vvawxsuqc=', max_length=128),
        ),
    ]
