# Generated by Django 5.0 on 2023-12-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$qGh0cNjgXOiLjGtOCFONKy$stMsfCIDsqIuM/Xf7aP73o8QlhTcYCNyl74/sWhgzsw=', max_length=128),
        ),
    ]
