# Generated by Django 5.0 on 2024-12-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$mF6yZPUCStP1AxhLBf7kZz$Fzia31xpVhxjZxulNzzyb7zcLtbn0ZwIZbI3+kCY0Zc=', max_length=128),
        ),
    ]
