# Generated by Django 5.0 on 2024-12-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$xjxkqNZhgyAWpVbQXBMwbS$BRmd4aLZjzVmKjwPDKh+Mkvn82Ch6HOdQARv14Yc9QA=', max_length=128),
        ),
    ]
