# Generated by Django 5.0 on 2024-12-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$0Ch3qhmdnKMyfWCHojekHe$rrblsDlP1XBK44dHER+pP0YtWD32/hz4tAozFK9jrVE=', max_length=128),
        ),
    ]
