# Generated by Django 5.0 on 2024-12-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$hwOFSb5gcgiu2S03fNorHH$2H4Saz2jTtsrJf/M+SoP0n/E3vS6ZBaQYnUJNORCTcY=', max_length=128),
        ),
    ]
