# Generated by Django 5.0 on 2024-12-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$NwK2w8UDNQHJDWP4B0m37I$ZI1PBK+/7jSqX+g97E2V1qS7rJ4sMs1MM8GNhmcU1Xk=', max_length=128),
        ),
    ]
