# Generated by Django 5.0 on 2025-01-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$jNDhXrQGShGgo8ZQr14AGQ$9g88naPLglDMEzzJ4DgdUtEPh9iNxTHD6vw0UJFh3hU=', max_length=128),
        ),
    ]
