# Generated by Django 5.0 on 2025-01-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_first_name_user_last_name_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$70WnRPjZdAHf8mRjlPExeO$vrJTYPgwUQb9wRjbHIexaaUoe6aYaHOmUIYPlJKBLd8=', max_length=128),
        ),
    ]
