# Generated by Django 5.0 on 2025-01-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_gender_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ending_verse_boundary',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='starting_verse_boundary',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$ZwYUOE3uCX9euV8ZBNqtvf$s+1/6FgzCsfLJCWCt14iu0t+1t04Y8RadXP5sReNSk0=', max_length=128),
        ),
    ]
