# Generated by Django 5.0 on 2025-01-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_ending_verse_boundary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$JN92nfmBAKhV6nhEeDScnT$V+szr5YGguSiVOVOb4FA8xXMpCqkfPskLSOXdBW2bNU=', max_length=128),
        ),
    ]
