# Generated by Django 5.0 on 2025-01-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$xRluW9GI0oTTHytEbvcTl7$3frmQZYFG7PcjMtEOhCyw+t4iOUcl3bJqUFOWlD9mmg=', max_length=128),
        ),
    ]
