# Generated by Django 5.0 on 2025-01-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$i6yVPtuvuhID5kFU4qXO5r$xLsvqnxN1kvUjQmXb705BR5RDhpuOstVAbqfNNCk4sc=', max_length=128),
        ),
    ]
