# Generated by Django 5.0 on 2025-01-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$iJKFoDTiqZqdhpDkkquUWR$wWd6qS+gC/BjYF6fBsvi5ZhLqaY54gz+u1f8XvwNR6A=', max_length=128),
        ),
    ]
