# Generated by Django 5.0 on 2025-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='peer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$UUAG5oyJqXFHTwdoOPoS52$g5QF6rcGb/TcygxunV5iZXSPKsP9wRhoZjdWNGFqoM4=', max_length=128),
        ),
    ]
