# Generated by Django 5.0 on 2025-02-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$0xMMbfisJRV0T6SBj9nZfk$lzN8VLc3wSso08xjbl1QD0RfDP6yEI9KPv6g+dGrA8E=', max_length=128),
        ),
    ]
