# Generated by Django 5.0 on 2025-02-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$wS1gnfB15oPp7RRycH4QYx$9nWWjoAprlkcHf5hgmkNdJWEkSNnGi1FGzlZe56KfBs=', max_length=128),
        ),
    ]
