# Generated by Django 5.0 on 2025-10-19 00:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available_for_match',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$54f1qNhz3Cu5tuutMgAKK1$EpusdShUpUeCqT2qeesRdoBbdl5hWCWgCvoUOSjyMCE=', max_length=128),
        ),
    ]
