# Generated by Django 5.0 on 2025-01-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_progress_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogressreport',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
