# Generated by Django 5.0 on 2023-12-15 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mushaf', '0002_mushaf_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MushafSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_page', models.IntegerField()),
                ('last_page', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('category_position', models.IntegerField()),
                ('mushaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushaf.mushaf')),
            ],
        ),
    ]
